### ISSUE TITLE
按自述文件部署后页面报Internal Server Error并持续自动刷新

### ISSUE THREAD

**Issue by ZeusGamingPlay** [HFIProgramming/custom-uptimerobot#10]
环境centos6 PHP7.0 Nginx1.12.1
CURL结果：
[root@ZeusGaming ~]# curl stats.uptimerobot.com
<a href="https://stats.uptimerobot.com/">Moved Permanently</a>.

**Comment by NeverBehave** [comment]
可以的话发一下地址
或者访问`api/?function=status&pagenumber=1&sorttype=1`看看返回结果是什么

**Comment by ZeusGamingPlay** [comment]
@NeverBehave https://stats.zeusgaming.tk

{"psp":{"monitors":[{"id":779510214,"friendly_name":"Airport","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 46 mins.","dateTimeStr":"2017-10-08 01:09:25","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507424965000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510222,"friendly_name":"HK Gaming 1","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 40 mins.","dateTimeStr":"2017-10-08 01:14:36","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425276000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510216,"friendly_name":"JP 1","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 44 mins.","dateTimeStr":"2017-10-08 01:10:35","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425035000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510217,"friendly_name":"JP 2","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 44 mins.","dateTimeStr":"2017-10-08 01:10:59","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425059000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510221,"friendly_name":"US 1","customuptimeranges":[{"label":"success","ratio":"98.820"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"98.820"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"0 hrs, 51 mins.","dateTimeStr":"2017-10-08 01:13:36","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425216000},{"statusStr":"down","durationStr":"0 hrs, 15 mins.","dateTimeStr":"2017-10-08 02:05:14","reasonStr":"No Response","reasonTitle":"No Response","label":"danger","timestamp":1507428314000},{"statusStr":"up","durationStr":"20 hrs, 34 mins.","dateTimeStr":"2017-10-08 02:20:36","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507429236000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510218,"friendly_name":"US 2","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 43 mins.","dateTimeStr":"2017-10-08 01:12:03","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425123000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510219,"friendly_name":"US 3","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 42 mins.","dateTimeStr":"2017-10-08 01:12:30","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425150000}],"status":2,"statusLabel":"success","statusNumber":2},{"id":779510220,"friendly_name":"US 4","customuptimeranges":[{"label":"success","ratio":"100.00"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"},{"label":"empty","ratio":"0.000"}],"oneWeekRange":{"label":"success","ratio":"100.00"},"typeStr":"ping","intervalMin":5,"allLogs":[{"statusStr":"up","durationStr":"21 hrs, 42 mins.","dateTimeStr":"2017-10-08 01:13:06","reasonStr":"Successful Response","reasonTitle":"Successful Response","label":"success","timestamp":1507425186000}],"status":2,"statusLabel":"success","statusNumber":2}],"name":"GZNS状态发布页","logo":null,"url_key":"08w7Ki6rj","hide_ur_links":false,"sort":1,"custom_css":"","announcements":[],"monitorCount":8,"latestDownTimeStr":"It was recorded (for the monitor US 1) on 2017-10-08 02:05:14 and the downtime lasted for 0 hrs, 15 mins.","latestDownLog":{"type":1,"datetime":1507428314,"duration":922,"reason":{"code":"444444","detail":"No Response"},"mon":{"friendly_name":"US 1"}},"hasActiveAnnounce":false,"activeAnnouncements":0,"firstAnnounceTitle":null,"firstAnnounceDescInline":null,"pspStats":{"ratios":{"l1":{"label":"success","ratio":"99.852"},"l7":{"label":"success","ratio":"99.852"},"l30":{"label":"success","ratio":"99.852"}},"counts":{"up":8,"down":0,"paused":0}},"downCount":0},"stat":"ok","days":["08 Oct","07 Oct","06 Oct","05 Oct","04 Oct","03 Oct","02 Oct"]}

**Comment by ZeusGamingPlay** [comment]
@NeverBehave 很奇怪，访问这个路径后页面就刷出来了。。。

**Comment by ZeusGamingPlay** [comment]
@NeverBehave 关闭页面后再次刷新，又挂了。。。

**Comment by NeverBehave** [comment]
未按照要求修改名字
参考 https://github.com/HFIProgramming/custom-uptimerobot/issues/8#issuecomment-326174209
 解决
@liwanglin12 可能要整理一份命名需求到readme.md

**Comment by ZeusGamingPlay** [comment]
@NeverBehave  “/”也需要输入吗，LWL建立的状态页面目前似乎无法正常访问

**Comment by NeverBehave** [comment]
是的，并且LWL的状态页目前正常

**Comment by ZeusGamingPlay** [comment]
@NeverBehave 全局代理状态下，https://status.lwl12.com/ 无法正常访问，Chrome提示ERR_CONNECTION_CLOSED
只有Uptime Robot提供的页面是正常的
https://stats.uptimerobot.com/Elw4jFLZ

**Comment by lwl12** [comment]
@metowolf

**Comment by ZeusGamingPlay** [comment]
@NeverBehave 现在执行 api/?function=status&pagenumber=1&sorttype=1 返回404

> Something goes Wrong! Try again Later :( [Code 404]

**Comment by NeverBehave** [comment]
检查网络把，可能是被屏蔽了
详见更新后的Readme 2cf328d

**Comment by ZeusGamingPlay** [comment]
请问现在项目还在维护嘛？
目前根据版本手册部署后连页面都无法正常显示。。。
https://status.gzns.tech

**Comment by NeverBehave** [comment]
@ZeusGamingPlay 这个问题是因为 css.net 变更了地址造成的，稍后修复

**Comment by NeverBehave** [comment]
9eae7575393631ea8edcbf06e1186d9c4bed9d9a
8bb9891e3a017bc0ac4972680afcc6579e586f27
21f055f0e5cd10b014846013867e93a01fcc9ead

感谢反馈，如果还有问题请重新开启这个issue。

**Comment by ZeusGamingPlay** [comment]
CSS的问题解决了，但最早开启这个issue的问题依旧
一直报Internal server error，并不断自动刷新页面。
已确认conf.php和info.php设置无误，缓存目录给777 www:www 权限
且绝对目录末尾写了/

**Comment by NeverBehave** [comment]
@ZeusGamingPlay 

如果是读写问题，是会爆500。
如果在清理缓存后，第一次载入时间花费较长并报错，可以确认是网络问题
否则，请确认安装了php-curl

**Comment by ZeusGamingPlay** [comment]
根据phpinfo打印出的数据，php curl是开启的版本为7.29.0
网络的话，可以正常Ping通uptimerobot的官网，curl解析也正常

**Comment by NeverBehave** [comment]
正在检查，最近比较忙可能会延后，请见谅

**Comment by ZeusGamingPlay** [comment]
麻烦了，我刚刚再次检查了一遍环境应该是没有问题的，参照之前的issue我将唯一Monitor的名字改成了Airport/Website/SG_Cloudflare，目测应该是符合命名规则的吧？
