### ISSUE TITLE
无限500

### ISSUE THREAD

**Issue by asuna** [HFIProgramming/custom-uptimerobot#8]
Debian jessie nginx 1.13.3 + php5.6出现500
nginx一直报如下错误:：
````bash
2017/08/21 00:33:12 [error] 13610#0: *1460823 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '>' in /usr/share/nginx/uptimerobot/api/Content.php on line 52" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: stats.kuroy.me, request: "GET /api/?function=status&pagenumber=1&sorttype=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "stats.kuroy.me", referrer: "https://stats.kuroy.me/"
````

**Comment by NeverBehave** [comment]
@liwanglin12 似乎是你那一段的问题，我还没部署你的版本不如你来看看？

**Comment by NeverBehave** [comment]
目前还是有这个问题吗？可以尝试切换一下PHP7吗？

**Comment by lwl12** [comment]
我猜PHP版本过低
@metowolf

**Comment by asuna** [comment]
换成了php7.1 + nginx 1.13.4，数据好像是取到了，但是页面上没有显示。使用默认的pageId的时候正常显示没有问题。
![](https://ooo.0o0.ooo/2017/08/30/59a6b5853fd55.png)

**Comment by NeverBehave** [comment]
@asuna
抱歉，似乎昨天邮件回复没有成功
请检查您的`Monitor`名字是否正确
规范：`Name/Section_Name/Location`
Location对于相同的`Section_Name`必须一致，具体请查找手册
同时感谢您在PHP5.6环境下测试了本项目

**Comment by NeverBehave** [comment]
1294fef 添加了PHP版本说明

**Comment by asuna** [comment]
👍 It works!
确实是Monitor名字不对，感谢两位帮助解决。
