### ISSUE TITLE
一打开就错误？

### ISSUE THREAD

**Issue by LynMoe** [HFIProgramming/custom-uptimerobot#9]
之前成功过一个，不知道什么时候开始就一直报错，重新安装也一样。diy跟我差不多时间安的貌似也不行了
我的 status.xiaolin.in  ,DIY的 prprpr.me

**Comment by NeverBehave** [comment]
在服务器上curl一下官方的API看看能不能获取到信息
有的时候是官方抽风或者你的IP被屏蔽了

**Comment by LynMoe** [comment]
php版本是7.1,nginx没报错

**Comment by XiaoLin0815** [comment]
哦吼

**Comment by LynMoe** [comment]
api.uptimerobot.com可以获取到
stats.uptimerobot.com超时

**Comment by NeverBehave** [comment]
我们用的是第二个网页接口，所以应该是您的服务器IP被屏蔽了
请尝试SNI代理（随意种类，SNI方便）或者等待我们的API版本

**Comment by LynMoe** [comment]
好的谢谢
